# Generated by Django 3.2.7 on 2021-09-11 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=120, null=True)),
                ('author', models.CharField(max_length=120, null=True)),
                ('preis', models.CharField(max_length=120, null=True)),
                ('katalog', models.CharField(choices=[('Die Abenteuer', 'Die Abenteuer'), ('historisch', 'historisch'), ('draman', 'draman'), ('politisch', 'politisch')], max_length=120, null=True)),
                ('beschreibung', models.CharField(max_length=120, null=True)),
                ('datum_create', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=120, null=True)),
                ('nachname', models.CharField(max_length=120, null=True)),
                ('telefon', models.CharField(max_length=120, null=True)),
                ('alt', models.IntegerField(max_length=30, null=True)),
                ('datum_create', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('liefern', 'liefern'), ('im fortschritt', 'im fortschritt'), ('unterweg', 'unterweg')], max_length=120, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.book')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.customer')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='bookstore.Tag'),
        ),
    ]
